export const projects = [
  {
    name: "Chatter[Box]",
    img: "",
    skills: ["MongoDB", "Express", "Node.js", "React", "Socket.io", "AWS S3"],
    details: "",
    site: "https://chatterbox-sei-55.herokuapp.com/",
  },
  { name: "Culinarian", img: "", skills: [], details: "", site: "" },
  { name: "StudySmart", img: "", skills: [], details: "", site: "" },
  { name: "Othello", img: "", skills: [], details: "", site: "https://tungolra.github.io/Othello/" },
  { name: "Book Collector", img: "", skills: [], details: "", site: "" },
];
export const skills = [
  { skill: "HTML5", img: "https://i.imgur.com/xMMSqAc.png" },
  { skill: "CSS3", img: "https://i.imgur.com/jTNhsgg.png" },
  { skill: "Materialize", img: "https://i.imgur.com/kLtV7aP.png" },
  { skill: "Material UI", img: "https://i.imgur.com/nQneTU6.png" },
  { skill: "Bootstrap", img: "https://i.imgur.com/NsKingN.png" },
  { skill: "React", img: "https://i.imgur.com/I9A7c4b.png" },
  { skill: "Redux", img: "https://i.imgur.com/B5jiJo7.png" },
  { skill: "Node.js", img: "https://i.imgur.com/SqYTp68.png" },
  { skill: "Javascript", img: "https://i.imgur.com/ckfbsq5.png" },
  { skill: "MongoDB", img: "https://i.imgur.com/a0RoQoD.png" },
  { skill: "Mongoose ODM", img: "https://i.imgur.com/BPb25o6.png" },
  { skill: "PostgreSQL", img: "https://i.imgur.com/kqTfCNX.png" },
  { skill: "Heroku", img: "https://i.imgur.com/TQ5qUGp.png" },
  { skill: "Git", img: "https://i.imgur.com/P6KIeEm.png" },
  { skill: "AWS S3", img: "https://i.imgur.com/n3fTnNv.png" },
  { skill: "Django", img: "https://i.imgur.com/CTDcDh6.png" },
  { skill: "Python", img: "https://i.imgur.com/ofIVvdH.png" },
  { skill: "Express", img: "https://i.imgur.com/jTNhsgg.png" },
  { skill: "Socket.io", img: "https://i.imgur.com/ozEa6Uk.png" },
];
